name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      # Vérifier le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'

      # Installer les dépendances
      - name: Install Dependencies
        run: npm install

      # Construire le package
      - name: Build Package
        run: npm run build

      # Minifier le package
      - name: Minify Package
        run: npm run minify

      # Publier sur npm
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Incrémenter la version après publication
      - name: Increment version
        id: version-bump
        run: |
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version to $(node -p \"require('./package.json').version\")"
          git push origin main

      # Créer un tag GitHub correspondant à la version
      - name: Create GitHub Tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin --tags
